### ISSUE TITLE
Getting a "Cannot read an array length because "bytes" are null" error, whenever I try to sync local and remote workspaces

### ISSUE THREAD

**Issue by kamilatte** [Defeatomizer/MCreatorVCSPlugin#14]
### Issue description

When I try syncing local and remote workspaces, I get a error mentioned in the title.

### How to reproduce this issue?

1. connect a remote workspace.
2. Try syncing.

### Operating system

macOS

### Details

MCreator version: [2023.3 / branch:master]
Plugin version: [2023.3.1]

### Logs

https://gist.github.com/alwayshyper/efd962e5da1a565eac0c61e6818a5a92

**Comment by Defeatomizer** [comment]
Seems your main workspace file has been deleted on the remote branch. I'll push a fix for such situations a little bit later. For now, you can try adding the `<mod_id>.mcreator` file back to the repository root from one of commits where it is present and syncing again.
