### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by sashaD12** [Defeatomizer/MCreatorVCSPlugin#17]
### Issue description

please help, it says that it was not possible to log in, but I wrote everything down correctly

### How to reproduce this issue?

1

### Operating system

Windows

### Details

2023.3

### Remote repository

https://github.com/sashaD12/moder.git

### Logs

https://github.com/sashaD12/moder.git

**Comment by sashaD12** [comment]
![image](https://github.com/Defeatomizer/MCreatorVCSPlugin/assets/137435076/18e6a350-27c7-49a0-9e07-50ff2896dd33)

**Comment by Defeatomizer** [comment]
Is your remote repository located on GitHub? If so, you would need to create an access token with all permissions from **repo** category and use it for authorization.

**Comment by Defeatomizer** [comment]
Your remote repository is located on GitHub, so you would need to create an access token with all permissions from **repo** category and use it for authentication.

**Comment by sashaD12** [comment]
can you help because I honestly don't understand how to do it

**Comment by Defeatomizer** [comment]
Got to your account settings page -> **Developer settings** -> **Personal access tokens** -> **Tokens (classic)** -> **Generate new token** -> **Generate new token (classic)**, then check/enable `repo` permissions category and fill in a desired expiration date and brief description. You will then be able to copy the token string once.

**Comment by sashaD12** [comment]
does this token need to be kept in mkriator?

**Comment by Defeatomizer** [comment]
If you don't plan to store the token somewhere else as well - yes (because GitHub won't let you see the token again).

**Comment by sashaD12** [comment]
Thank you very much, it helped
