### ISSUE TITLE
I can't connect to my GitHub repo

### ISSUE THREAD

**Issue by Minetrio1256** [Defeatomizer/MCreatorVCSPlugin#21]
### Issue description

I created a classic token with the asked permission with the pop up to connect and when I want to upload files to the git repo 
I get a access denied error.

### How to reproduce this issue?

Connect to a git with the ask permission.
Get the error.

### Operating system

macOS

### Details

Mcreator 2023.3

**Comment by Defeatomizer** [comment]
So you used the token in the password field and the authentification failed? If this is the case, could you possibly attach app logs after this happens (`<user.home>/.mcreator/logs/mcreator.log`, written after app closed)?

**Comment by Minetrio1256** [comment]
I run on a Mac so where is this log file?

**Comment by Defeatomizer** [comment]
> you can use command shift dot to reveal hidden files or command shift g to go to it directly

**Comment by Minetrio1256** [comment]
Here is the log.
[mcreator.log](https://github.com/Defeatomizer/MCreatorVCSPlugin/files/13629269/mcreator.log)

**Comment by Defeatomizer** [comment]
> Caused by: org.eclipse.jgit.errors.NoRemoteRepositoryException: https;//github.com/minetrio1256/backrooms.git: not found.

You used a wrong symbol (semicolon instead of colon).

**Comment by Minetrio1256** [comment]
Thank you for your help :)
