### ISSUE TITLE
Remote Repo Buttons not showing

### ISSUE THREAD

**Issue by SkyKingPX** [Defeatomizer/MCreatorVCSPlugin#23]
### Issue description

I installed the last version of MCreator and the plugin, but none of the buttons are showing.

![image](https://github.com/Defeatomizer/MCreatorVCSPlugin/assets/95442431/5f1e0ab8-26b3-455d-8c64-d24c2f66aa71)

### How to reproduce this issue?

Open Workspacea

### Operating system

Windows

### Details

MCreator: 2023.4
Plugin: 2023.3.1

### Remote repository

We wanted to work together with my friend.
https://github.com/SkyproPX/MC_end-etc.

**Comment by Defeatomizer** [comment]
> MCreator: 2023.4

The plugin has not been ported to this version yet.
