### ISSUE TITLE
Not compatible with 2023.3

### ISSUE THREAD

**Issue by BruhFanOfAll** [Defeatomizer/MCreatorVCSPlugin#26]
### Issue description

Hello, I have the same problem as Oofeiro.
I still use 2023.3 because of a NeoForge plugin, that's only available for that version. I've downloaded the plugin through GitHub. Me and my friend really want to make a MCreator mod together.
![image](https://github.com/Defeatomizer/MCreatorVCSPlugin/assets/158840140/887198bd-571b-4c85-8fef-e31da86eadf1)
![image](https://github.com/Defeatomizer/MCreatorVCSPlugin/assets/158840140/1ca28a72-d103-4474-93f3-d591212196c5)

### How to reproduce this issue?

Maybe you could try updating the 2023.3 version to the same one as MCreator's?

### Operating system

Windows

### Details

MCreator version: 2023.3.36712
Plugin version: 2023.3

**Comment by Defeatomizer** [comment]
Basing on the provided screenshots, Java plugins support was not enabled in the preferences.
