### ISSUE TITLE
github actions is not working corectly

### ISSUE THREAD

**Issue by Thunderrock424242** [Defeatomizer/MCreatorVCSPlugin#32]
### Issue description

so i am using github actions and after every file a commit I wanted to build a jar file of my mod but this keeps on happening 
![Screenshot 2024-06-05 171654](https://github.com/Defeatomizer/MCreatorVCSPlugin/assets/119463825/c91efc78-0f3e-476f-8206-316a5cc09eb9)

### How to reproduce this issue?

if you have a workspace set up actions then commit from m creator then it will fail

### Operating system

Windows

### Details

mcreator v 2024.1/ branch:master / plugin v latest one

### Remote repository

[here is the link](https://github.com/Thunderrock424242/Wilderness-Oddesy-api)

**Comment by Thunderrock424242** [comment]
ran debug mode
![Screenshot 2024-06-05 172247](https://github.com/Defeatomizer/MCreatorVCSPlugin/assets/119463825/a31fba9f-13e6-451c-a610-00173316e289)
is this a mcreator issue?

**Comment by Thunderrock424242** [comment]
nvm

**Comment by Defeatomizer** [comment]
Git is not related to GitHub Actions directly so this would need to be figured out manually.
> nvm

So the issue is resolved?

**Comment by Thunderrock424242** [comment]
Yes
