### ISSUE TITLE
Error occured when my friend tries to synchronize the workspace

### ISSUE THREAD

**Issue by R4phiR** [Defeatomizer/MCreatorVCSPlugin#33]
### Issue description

So, when my friend tries to synchronise the workspace after I made a commit, an error occured : "org.eclipse.jgit.lib.AnyObjectId.hashCode() because "id" is null"
I don't know how to fix that and i can't work with my friend anymore.. Do you have an idea ?

### How to reproduce this issue?

1. I create any thing, an item, a block, anything
2. I commit what I created
3. My friend tries to synchronize the workspace
4. The error occurs

### Operating system

Windows

### Details

MCreator version : 2024.1
Plugin version : 2024.1.3
Mod on NeoForge for 1.20.4 (20.4.223)

### Remote repository

It occurs in all of my repositories..

### Logs

Nothing on the logs but the message "Cannot invoke "org.eclipse.jgit.lib.AnyObjectId.hashCode()" because "id" is null" appears

**Comment by R4phiR** [comment]
First we thought it was because of plugins such as GeckoLib or CuriosAPI because they were installed but we tried without any of theses plugins and it was the same thing. We also tried on another workspace and another repository but it was the same. And we also reinstalled MCreator 3 times but nothing changed

**Comment by R4phiR** [comment]
ok we solved the problem, i don't know how we did that, but it works again now x)

**Comment by Defeatomizer** [comment]
Could you possibly try to describe your steps as they may help to prevent duplicate issues?

**Comment by R4phiR** [comment]
Ok so, it was our first time making a mod on a remote workspace so we didn't know how it was working. Basiclly we just did it wrong.. We created 2 different workspaces and linked the two workspace on the same repository instead of cloning the remote access..
Sorry if we wasted your time, but now we know and it's fixed !
