### ISSUE TITLE
push commit added runs to github

### ISSUE THREAD

**Issue by Thunderrock424242** [Defeatomizer/MCreatorVCSPlugin#37]
### Issue description

it added all my runs into github

### How to reproduce this issue?

play your mod
make some file changes 
then push commit.

### Operating system

Windows

### Details

mcreator 2024.3

### Remote repository

https://github.com/Thunderrock424242/Wilderness-Oddesy-api/compare/6118e615dca7...273bb680beed

**Comment by Defeatomizer** [comment]
Should be resolved by https://github.com/MCreator/MCreator/commit/b0b0d45ad64c5a42ce4378cd7bd64f40e4924245.
