### ISSUE TITLE
UI breaks on MacOS

### ISSUE THREAD

**Issue by brambleclaw1** [Defeatomizer/MCreatorVCSPlugin#5]
### Issue description

When using the plugin and loading a workspace the window turns white a freezes

### How to reproduce this issue?

1. Loaded MCreator with the plugin installed
2. Created a new workspace

### Operating system

macOS

### Details

MCreator Version: 2022.2
Plugin Version: 2023.2.1
Java version: 17.0.7

**Comment by KlemenDEV** [comment]
Checking https://github.com/Defeatomizer/MCreatorVCSPlugin/blob/master/src/main/java/net/mcreator/vcs/Launcher.java there is a lot of UI things happening on the async plugin thread that will inevitably lead to problems on macOS
