### ISSUE TITLE
Pushing to github fails with message "Invalid value: gpg.format=ssh"

### ISSUE THREAD

**Issue by Ethanadams642** [Defeatomizer/MCreatorVCSPlugin#8]
### Issue description

When I try to push changes to an empty github repository, the sync fails with this error:
![image](https://github.com/Defeatomizer/MCreatorVCSPlugin/assets/66756094/72bcf12a-6f0b-4ea6-9ff5-975949b21400)
![image](https://github.com/Defeatomizer/MCreatorVCSPlugin/assets/66756094/d1798613-4359-49d9-a122-1ecde1d9feff)

### How to reproduce this issue?

1. Configure the plugin with repo, username and gh token.
2. Attempt to sync local changes with remote workspace.

### Operating system

Linux

### Details

MCreator Version 2023.2
Plugin Version 2023.2.1

Endeavour OS
System git version: 2.41.0

### Logs

https://gist.github.com/Ethanadams642/c341a9dc7bf6f9bfaf7a66fcc65dc4c2

**Comment by Defeatomizer** [comment]
Unfortunately, SSH keys are [not supported by JGit](https://www.eclipse.org/forums/index.php?t=msg&th=1112207&goto=1856723) on its own at this moment, so they aren't planned to be included for now. You will need to use a key of another type.
